server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:4114/comments
    username: postgres
    password: amin2005
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
